uniffi::build_foreign_language_testcases!(
    // Kotlin tests
    "tests/kotlin/zcash_client_backend/address/recipient_address.kts",
    "tests/kotlin/zcash_client_backend/address/unified_address.kts",
    "tests/kotlin/zcash_client_backend/keys/unified_spending_key.kts",
    "tests/kotlin/zcash_client_backend/keys/unified_full_viewing_key.kts",
    "tests/kotlin/zcash_client_backend/encoding.kts",
    "tests/kotlin/orchard/diversifier_index.kts",
    "tests/kotlin/orchard/keys/orchard_diversifier.kts",
    "tests/kotlin/orchard/keys/orchard_full_viewing_key.kts",
    "tests/kotlin/orchard/keys/incoming_viewing_key.kts",
    "tests/kotlin/orchard/keys/spending_key.kts",
    "tests/kotlin/orchard/address.kts",
    "tests/kotlin/hdwallet/extended_key/extended_priv_key.kts",
    "tests/kotlin/hdwallet/key_index.kts",
    "tests/kotlin/zcash_primitives/legacy/keys/account_priv_key.kts",
    "tests/kotlin/zcash_primitives/legacy/keys/account_pub_key.kts",
    "tests/kotlin/zcash_primitives/legacy/transparent_address.kts",
    "tests/kotlin/zcash_primitives/sapling/value/note.kts",
    "tests/kotlin/zcash_primitives/sapling/sapling_ivk.kts",
    "tests/kotlin/zcash_primitives/sapling/diversifier.kts",
    "tests/kotlin/zcash_primitives/sapling/keys/extended_full_viewing_key.kts",
    "tests/kotlin/zcash_primitives/sapling/keys/viewing_key.kts",
    "tests/kotlin/zcash_primitives/sapling/keys/expanded_spending_key.kts",
    "tests/kotlin/zcash_primitives/sapling/keys/diversifiable_full_viewing_key.kts",
    "tests/kotlin/zcash_primitives/sapling/keys/outgoing_viewing_key.kts",
    "tests/kotlin/zcash_primitives/sapling/keys/full_viewing_key.kts",
    "tests/kotlin/zcash_primitives/sapling/payment_address.kts",
    "tests/kotlin/zcash_primitives/memo/memo_bytes.kts",
    "tests/kotlin/secp256k1/mod.kts",
    "tests/kotlin/test_support.kts",
    // Python tests
    "tests/python/test.py",
    "tests/python/sapling.py",
    "tests/python/orchard.py",
    // Ruby tests
    "tests/ruby/test.rb",
    "tests/ruby/sapling.rb",
    "tests/ruby/orchard.rb",
    // Swift tests
    "tests/swift/test.swift",
    "tests/swift/sapling.swift",
    "tests/swift/orchard.swift"
);
