/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package app

import kotlin.test.Test
import kotlin.test.assertEquals
import uniffi.zcash.*

class ZcashTest {
    @Test fun getAmount() {
        val amount = ZcashAmount(100)
        assertEquals(100, amount.value())
    }
}
