name: "Tag packages"

on:
  push:
    tags:
      - "*.*.*" # Must be a semver parseable tag
env:
  CARGO_TERM_COLOR: always

jobs:
  bindgen:
    uses: ./.github/workflows/bindgen.yml
    with:
      artifacts-storage-prefix: "publishing"
    secrets:
      languages: ${{ secrets.LANGUAGES }}

  build-packages:
    needs: bindgen
    uses: ./.github/workflows/packages.yml
    with:
      version: ${{ github.ref_name }}
      artifacts-storage-prefix: "publishing"
    secrets:
      git-user-name: ${{ secrets.GIT_USER_NAME }}
      git-user-email: ${{ secrets.GIT_USER_EMAIL }}
      kotlin-registry-url: ${{ secrets.KOTLIN_REGISTRY_URL }}
      kotlin-registry-username: ${{ secrets.KOTLIN_REGISTRY_USERNAME }}
      kotlin-registry-password: ${{ secrets.KOTLIN_REGISTRY_PASSWORD }}
      swift-git-repo-url: ${{ secrets.SWIFT_GIT_REPO_URL }}

  publish-packages:
    needs: build-packages
    uses: ./.github/workflows/publish.yml
    with:
      version: ${{ github.ref_name }}
      artifacts-storage-prefix: "publishing"
      dry-run: true ## Uncomment this for real publication.
    secrets:
      python-registry-url: ${{ secrets.PYTHON_REGISTRY_URL }}
      python-registry-username: ${{ secrets.PYTHON_REGISTRY_USERNAME }}
      python-registry-password: ${{ secrets.PYTHON_REGISTRY_PASSWORD }}

      ruby-registry-url: ${{ secrets.RUBY_REGISTRY_URL }}
      ruby-registry-token: ${{ secrets.RUBY_REGISTRY_TOKEN }}

      kotlin-registry-url: ${{ secrets.KOTLIN_REGISTRY_URL }}
      kotlin-registry-username: ${{ secrets.KOTLIN_REGISTRY_USERNAME }}
      kotlin-registry-password: ${{ secrets.KOTLIN_REGISTRY_PASSWORD }}

      swift-git-repo-url: ${{ secrets.SWIFT_GIT_REPO_URL }}
      swift-registry-url: ${{ secrets.SWIFT_REGISTRY_URL }}
      swift-registry-token: ${{ secrets.SWIFT_REGISTRY_TOKEN }}

  publish-docs:
    if: ${{ false }} ## Disabled, Publishing Github pages from CI is still beta feature, at the moment of this write this doesn't work.
    needs: publish-packages
    uses: ./.github/workflows/docs.yml
